Citizen.CreateThread(function()
    RegisterCommand("weapon",function(source)
        print("weapon")
    end)
    SetWeaponDamageModifier(
        'WEAPON_DAGGER', 
        0.13
    )
    SetWeaponDamageModifier(
        'WEAPON_BAT', 
        0.1
    )
    SetWeaponDamageModifier(
        'WEAPON_DAWEAPON_BOTTLEGGER', 
        0.13
    )
    SetWeaponDamageModifier(
        'WEAPON_CROWBAR', 
        0.13
    )
    SetWeaponDamageModifier(
        'WEAPON_UNARMED', 
        0.2
    )
    SetWeaponDamageModifier(
        'WEAPON_FLASHLIGHT', 
        0.1
    )
    SetWeaponDamageModifier(
        'WEAPON_GOLFCLUB', 
        0.1
    )
    SetWeaponDamageModifier(
        'WEAPON_HAMMER', 
        0.1
    )
    SetWeaponDamageModifier(
        'WEAPON_HATCHET', 
        0.13
    )
    SetWeaponDamageModifier(
        'WEAPON_KNIFE', 
        0.13
    )
    SetWeaponDamageModifier(
        'WEAPON_MACHETE', 
        0.13
    )
    SetWeaponDamageModifier(
        'WEAPON_SWITCHBLADE', 
        0.13
    )
    SetWeaponDamageModifier(
        'WEAPON_NIGHTSTICK', 
        0.1
    )
    SetWeaponDamageModifier(
        'WEAPON_WRENCH', 
        0.1
    )
    SetWeaponDamageModifier(
        'WEAPON_BATTLEAXE', 
        0.13
    )
    SetWeaponDamageModifier(
        'WEAPON_POOLCUE', 
        0.1
    )
    SetWeaponDamageModifier(
        'WEAPON_STONE_HATCHET', 
        0.13
    )
end)
